### ISSUE TITLE
HOMEASSISTANT - NODERED

### ISSUE THREAD

**Issue by lucaskhourybr** [bitpool/edge-bacnet#1]
O nó Gateway não apresenta as Network Interface. 
Alguma solução ?

**Comment by dblanchie** [comment]
> O nó Gateway não apresenta as Network Interface.
> Alguma solução ?


Please send through OS details, did you restart node red after deploying gateway node?

**Comment by lucaskhourybr** [comment]
Estou rodando o node Red no sistema HAOS ( HomeAssistant ) . Já reinicei o NODERED e já reiniciei o servidor HAOS , porém sem sucesso.

**Comment by lucaskhourybr** [comment]
Alguem tem alguma solução ja tentei diversas vezes porem sem sucesso

**Comment by dblanchie** [comment]
> Alguem tem alguma solução ja tentei diversas vezes porem sem sucesso

I recommend running nodered on a seperate instance, we have tested on Ubuntu Server and Windows to date. You can grab the entire docker container from the link in the repo

**Comment by lucaskhourybr** [comment]
Precisaria utilizar na plataforma no HOMEASSISTANT devido as integrações que estou criando .
Em instancia separada funciona mesmo conforme comentando .

**Comment by bitpool-dev** [comment]
Hi @lucaskhourybr  - we currently do not support Home assistant os. Please use node-red directly on linux or windows, or docker for linux.

**Comment by gnlgrim** [comment]
For anyone interested. I got this working .
I am busy writing up a documentation for the whole process.
But in a quick way.    do everything as normal, but access node red through Home assistant IP and the port under the add-on configuration settings ( usually 1880 ) please remember to add a username and password.
You have to choose All interfaces under interface settings and set Broadcast Address to 255.255.255.255

Hope this helps. 
Will send everything over to devs when done so they can add it to documentation

**Comment by lucaskhourybr** [comment]
Como que você realizou isso ainda estou com mesmo problema 2024 homeassistant/nodered não consigo visualizar as portas de rede.
![a](https://github.com/user-attachments/assets/9c198e31-0da1-4e88-b867-a5bdcc0bc4e1)

**Comment by gnlgrim** [comment]
you cannot access node red from inside home assistant.
for some odd reason if you do it this way home assistant blocks interface
You have to access it from node red external IP.
To check the port . go into home assistant 
settings
add ons
node red.
configuration
scroll to bottom and check port settings
""node red documentation can help with this ""
then type home assistant ip address followed by node red port
example:  192.168.1.113:1880
then you will be able to pick up Network interface

**Comment by bitpool-dev** [comment]
Can you try with the bacnet server enabled? There is currently a bug with version 1.4.1 where the node stops / network interfaces disappear if the bacnet server is not enabled ? This will be resolved with version 1.4.2

**Comment by lucaskhourybr** [comment]
Boa noite.

Estou utilizando o IP e a porta 1880 , porém mesmo assim ainda nãe me apresenta as placas de rede, conforme imagem abaixo

![image](https://github.com/user-attachments/assets/db881d38-3f9a-4f88-9fcb-df76916f59eb)



Além disso ja habilitei o servidor bacnet conforme imagem abaixo e reinciei ele porém sem sucesso ainda.

![image](https://github.com/user-attachments/assets/14ce270d-9a14-40f8-8043-fcdcf31cb601)

**Comment by bitpool-dev** [comment]
Are you able to try again with the version 1.4.2 ?

**Comment by lucaskhourybr** [comment]
@bitpool-dev mesmo na versão 1.4.3 atual não funciona infelizmente, não aparece a porta de rede.
