### ISSUE TITLE
Create a sub-device

### ISSUE THREAD

**Issue by UnCanard14** [bitpool/edge-bacnet#22]
I'm relatively new to the Bacnet protocol but I was wondering if there's a way to do something like this :
![image](https://github.com/bitpool/edge-bacnet/assets/25232448/c77f5e7a-213f-4ebd-86d9-e5b7c62de01b)
 with your node, or is specific equipment required?

**Comment by dblanchie** [comment]
these are MSTP bacnet device which are rs485 2 wire devices, we support discovery of these devices. for BACnet server this can only be done from the IP device you are running node on, we dont support BACnet server over MSTP. Also note you will see a link to our discord which maybe better for you for flowing chat :)

**Comment by UnCanard14** [comment]
Hello it works thank you for your answer, it enlightened me! Ah yes, that would be nice, where can I find this link? :)

**Comment by bitpool-dev** [comment]
Hey @UnCanard14 - yes there are many BACnet MS/TP devices available from various manufacturers, happy shopping ! 

You can join our discord here if you are interested:    https://discord.gg/G4NFaMtqga

Closing this issue.
