### ISSUE TITLE
"Read" no longer work after node-red restart

### ISSUE THREAD

**Issue by DSt00** [bitpool/edge-bacnet#3]
Hi,

While testing the flow following the youtube tutorial, the read function no longer works properly after restart of the node-red.

The gateway is finding my devices
![image](https://github.com/bitpool/edge-bacnet/assets/74915097/8573366c-da5a-4a26-8129-bb4cc8634817)
but the read function is empty, even though it says 2 devices found
![image](https://github.com/bitpool/edge-bacnet/assets/74915097/e20e3429-07cc-4b13-b9cf-c1cb28043655)

Any ideas on how to troubleshoot?
I'm currently testing it on Win10 virtual machine before implementing it on an edge device. After the issue occur I tried it on freshly installed node-red on my local machine, but there it cannot even find the devices.
![image](https://github.com/bitpool/edge-bacnet/assets/74915097/57e22aee-8fcb-406f-8ec6-7f6b3fa2fbc1)

**Comment by dblanchie** [comment]
Conversation moved to discord for diagnosis will update in comments when resolved

**Comment by bitpool-dev** [comment]
Issue surrounding hyper v installation. A solution was found via discord chat. Closing this case.
