### ISSUE TITLE
Description fields not read into read list any more

### ISSUE THREAD

**Issue by HarvUK** [bitpool/edge-bacnet#31]
**Describe the bug**
In newer version of the module, the description field is not present in the read list.

Example of existing install
![image](https://github.com/user-attachments/assets/19217738-3175-47b6-9a98-6486cecd5797)

Example from new install
![image](https://github.com/user-attachments/assets/5414c54e-b828-467e-a550-f9ac753a3265)

The new install is clean install of v1.4.1

**To Reproduce**
Install, discover devices

**Expected behavior**

Description fields to be present.

**Screenshots**

**System Information (please complete the following information):**
 - OS: Raspberry Pi OS
 - Browser Chromium
 - Version 1.4.1
 - Node-RED version: 4.0.2 
 - NodeJS version: 

**Are you running Node-RED in a docker container or directly on the operating system or virtual machine?**
On Pi

**Please provide a dump of the Node-RED error log with the Error logging and Device Found check box options enabled (found in _gateway_ node - _Discovery_ tab) if applicable:**
 

**Additional context**

**Comment by HarvUK** [comment]
Update:

I have looked on the device again today, and it appears that the description field is now updated.

I don't know why though - can the dev explain please - did I just need to wait for a points discovery?

![image](https://github.com/user-attachments/assets/564fca50-3b1b-46c8-922b-6d18111ab385)

**Comment by bitpool-dev** [comment]
Hi @HarvUK   -  did I just need to wait for a points discovery? -  yes.

The point discovery flow has been adjusted to do an initial iteration of all points, only retrieving objectName and presentValue. After which it will backfill with additional properties. Reason for this is we have had sites with 500+ devices, some of which have 20k+ points. So this adjustment makes for a more responsive tree build out. 

If you want all of the information sooner, you can reduce the Object Discovery Frequency, or manual Right Click -> Update Points  on your devices.

**Comment by HarvUK** [comment]
This makes sense - many thanks.
